# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-23 12:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pesanan', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Transaksi',
            new_name='Pesanan',
        ),
    ]
