# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-24 12:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pesanan', '0002_auto_20170424_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pesanan',
            name='harga',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
