# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-13 06:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pesan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pesan',
            name='biaya_pengiriman',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='pesan',
            name='diskon',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='pesan',
            name='harga',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='pesan',
            name='kategori_harga',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='pesan',
            name='ratingproduk',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='pesan',
            name='ratingtoko',
            field=models.PositiveIntegerField(),
        ),
    ]
