# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-17 04:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pesan', '0003_auto_20170717_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pesan',
            name='waktu_pembelian',
            field=models.DateField(),
        ),
    ]
