# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-19 10:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pelanggan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('no_telepon', models.CharField(blank=True, max_length=30)),
                ('jenis_kelamin', models.CharField(choices=[('pria', 'Pria'), ('wanita', 'Wanita')], max_length=10)),
                ('kabupaten', models.CharField(choices=[('KabupatenAsahan', 'Kabupaten Asahan'), ('kabupatenBatubara', 'Kabupaten Batubara'), ('KabupatenDairi', 'Kabupaten Dairi'), ('KabupatenDeliSerdang', 'Kabupaten Deli Serdang'), ('KabupatenHumbangHasudutan', 'Kabupaten Humbang Hasudutan'), ('KabupatenKaro', 'Kabupaten Karo'), ('KabupatenLabuhanBatu', 'Kabupaten Labuhan Batu'), ('KabupatenLabuhanBatuSelatan', 'Kabupaten Labuhan Batu Selatan'), ('KabupatenLabuhanBatuUtara', 'Kabupaten Labuhan Batu Utara'), ('KabupatenHumbangLangkat', 'Kabupaten Humbang Langkat'), ('KabupatenMandailingNatal', 'Kabupaten Mandailing Natal'), ('KabupatenNias', 'Kabupaten Nias'), ('KabupatenNiasBarat', 'Kabupaten Nias Barat'), ('KabupatenNiasSelatan', 'Kabupaten Nias Selatan'), ('KabupatenNiasUtara', 'Kabupaten Nias Utara'), ('KabupatenPadangLawas', 'Kabupaten Padang Lawas'), ('KabupatenPadangLawasUtara', 'Kabupaten Padang Lawas Utara'), ('KabupatenPakpakBharat', 'Kabupaten Pakpak Bharat'), ('KabupatenSamosir', 'Kabupaten Samosir'), ('KabupatenSerdangBedagai', 'Kabupaten Serdang Bedagai'), ('KabupatenTapanuli', 'Kabupaten Tapanuli'), ('kabupatenTapanuliSelatan', 'Kabupaten Tapanuli Selatan'), ('KabupatenTapanuliTengah', 'Kabupaten Tapanuli Tengah'), ('KabupatenTapanuliUtara', 'Kabupaten Tapanuli Utara'), ('KotaBinjai', 'Kota Binjai'), ('KotaGunungSitoli', 'Kota Gunung Sitoli'), ('KotaMedan', 'Kota Medan'), ('KotaPadangSidempuan', 'Kota Padang Sidempuan'), ('KotaPematangSiantar', 'Kota Pematang Siantar'), ('KotaSibolga', 'Kota Sibolga'), ('KotaTanjungBalai', 'Kota Tanjung Balai'), ('KotaTebingTinggi', 'Kota Tebing Tinggi')], max_length=32)),
                ('alamat', models.TextField(blank=True)),
                ('kodepos', models.CharField(max_length=5)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
