# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-24 10:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pohonkeputusan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kategoriharga', models.PositiveIntegerField()),
                ('ongkoskirim', models.PositiveIntegerField()),
                ('diskon', models.PositiveIntegerField()),
                ('ratingproduk', models.PositiveIntegerField()),
                ('ratingtoko', models.PositiveIntegerField()),
                ('label', models.PositiveIntegerField()),
                ('pelanggan', models.PositiveIntegerField()),
            ],
        ),
    ]
