# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-03 11:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pohonkeputusan', '0002_pohonkeputusan_alamat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pohonkeputusan',
            old_name='alamat',
            new_name='perdaerah',
        ),
    ]
