# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-20 01:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pohonkeputusan', '0003_auto_20170603_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='pohonkeputusan',
            name='waktu_transaksi',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
