# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-20 01:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pohonkeputusan', '0004_pohonkeputusan_waktu_transaksi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pohonkeputusan',
            name='waktu_transaksi',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
