# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-07 01:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ongkoskirim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kabupaten_asal', models.CharField(choices=[('Kabupaten Asahan', 'Kabupaten Asahan'), ('kabupaten Batubara', 'Kabupaten Batubara'), ('Kabupaten Dairi', 'Kabupaten Dairi'), ('Kabupaten Deli Serdang', 'Kabupaten Deli Serdang'), ('Kabupaten Humbang Hasudutan', 'Kabupaten Humbang Hasudutan'), ('Kabupaten Karo', 'Kabupaten Karo'), ('Kabupaten Labuhan Batu', 'Kabupaten Labuhan Batu'), ('Kabupaten Labuhan Batu Selatan', 'Kabupaten Labuhan Batu Selatan'), ('Kabupaten Labuhan Batu Utara', 'Kabupaten Labuhan Batu Utara'), ('Kabupaten Humbang Langkat', 'Kabupaten Humbang Langkat'), ('Kabupaten Mandailing Natal', 'Kabupaten Mandailing Natal'), ('Kabupaten Nias', 'Kabupaten Nias'), ('Kabupaten Nias Barat', 'Kabupaten Nias Barat'), ('Kabupaten Nias Selatan', 'Kabupaten Nias Selatan'), ('Kabupaten Nias Utara', 'Kabupaten Nias Utara'), ('Kabupaten Padang Lawas', 'Kabupaten Padang Lawas'), ('Kabupaten Padang Lawas Utara', 'Kabupaten Padang Lawas Utara'), ('Kabupaten Pakpak Bharat', 'Kabupaten Pakpak Bharat'), ('Kabupaten Samosir', 'Kabupaten Samosir'), ('Kabupaten Serdang Bedagai', 'Kabupaten Serdang Bedagai'), ('Kabupaten Tapanuli', 'Kabupaten Tapanuli'), ('kabupaten Tapanuli Selatan', 'Kabupaten Tapanuli Selatan'), ('Kabupaten Tapanuli Tengah', 'Kabupaten Tapanuli Tengah'), ('Kabupaten Tapanuli Utara', 'Kabupaten Tapanuli Utara'), ('Kota Binjai', 'Kota Binjai'), ('Kota Gunung Sitoli', 'Kota Gunung Sitoli'), ('Kota Medan', 'Kota Medan'), ('Kota Padang Sidempuan', 'Kota Padang Sidempuan'), ('Kota Pematang Siantar', 'Kota Pematang Siantar'), ('Kota Sibolga', 'Kota Sibolga'), ('Kota Tanjung Balai', 'Kota Tanjung Balai'), ('Kota Tebing Tinggi', 'Kota Tebing Tinggi')], max_length=32)),
                ('kabupaten_tujuan', models.CharField(choices=[('Kabupaten Asahan', 'Kabupaten Asahan'), ('kabupaten Batubara', 'Kabupaten Batubara'), ('Kabupaten Dairi', 'Kabupaten Dairi'), ('Kabupaten Deli Serdang', 'Kabupaten Deli Serdang'), ('Kabupaten Humbang Hasudutan', 'Kabupaten Humbang Hasudutan'), ('Kabupaten Karo', 'Kabupaten Karo'), ('Kabupaten Labuhan Batu', 'Kabupaten Labuhan Batu'), ('Kabupaten Labuhan Batu Selatan', 'Kabupaten Labuhan Batu Selatan'), ('Kabupaten Labuhan Batu Utara', 'Kabupaten Labuhan Batu Utara'), ('Kabupaten Humbang Langkat', 'Kabupaten Humbang Langkat'), ('Kabupaten Mandailing Natal', 'Kabupaten Mandailing Natal'), ('Kabupaten Nias', 'Kabupaten Nias'), ('Kabupaten Nias Barat', 'Kabupaten Nias Barat'), ('Kabupaten Nias Selatan', 'Kabupaten Nias Selatan'), ('Kabupaten Nias Utara', 'Kabupaten Nias Utara'), ('Kabupaten Padang Lawas', 'Kabupaten Padang Lawas'), ('Kabupaten Padang Lawas Utara', 'Kabupaten Padang Lawas Utara'), ('Kabupaten Pakpak Bharat', 'Kabupaten Pakpak Bharat'), ('Kabupaten Samosir', 'Kabupaten Samosir'), ('Kabupaten Serdang Bedagai', 'Kabupaten Serdang Bedagai'), ('Kabupaten Tapanuli', 'Kabupaten Tapanuli'), ('kabupaten Tapanuli Selatan', 'Kabupaten Tapanuli Selatan'), ('Kabupaten Tapanuli Tengah', 'Kabupaten Tapanuli Tengah'), ('Kabupaten Tapanuli Utara', 'Kabupaten Tapanuli Utara'), ('Kota Binjai', 'Kota Binjai'), ('Kota Gunung Sitoli', 'Kota Gunung Sitoli'), ('Kota Medan', 'Kota Medan'), ('Kota Padang Sidempuan', 'Kota Padang Sidempuan'), ('Kota Pematang Siantar', 'Kota Pematang Siantar'), ('Kota Sibolga', 'Kota Sibolga'), ('Kota Tanjung Balai', 'Kota Tanjung Balai'), ('Kota Tebing Tinggi', 'Kota Tebing Tinggi')], max_length=32)),
                ('biaya', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
