# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kategori',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='produk',
            name='slug',
        ),
        migrations.AlterField(
            model_name='kategori',
            name='nama',
            field=models.CharField(db_index=True, max_length=200, unique=True),
        ),
    ]
