# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-10 07:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produk',
            name='kategorudiskon',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='produk',
            name='kategoruongkoskirim',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='produk',
            name='kategoruratingproduk',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='produk',
            name='kategoruratingtoko',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='produk',
            name='kmeansharga',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
