# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-10 07:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20170510_1408'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produk',
            old_name='kategorudiskon',
            new_name='kategoridiskon',
        ),
        migrations.RenameField(
            model_name='produk',
            old_name='kategoruongkoskirim',
            new_name='kategoriongkoskirim',
        ),
        migrations.RenameField(
            model_name='produk',
            old_name='kategoruratingproduk',
            new_name='kategoriratingproduk',
        ),
        migrations.RenameField(
            model_name='produk',
            old_name='kategoruratingtoko',
            new_name='kategoriratingtoko',
        ),
    ]
