# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-16 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20170510_1415'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rekomendasi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produk_id', models.PositiveIntegerField()),
                ('produk_nama', models.CharField(db_index=True, max_length=200)),
                ('produk_gambar', models.CharField(db_index=True, max_length=200)),
                ('produk_harga', models.DecimalField(decimal_places=0, max_digits=10)),
                ('produk_diskon', models.DecimalField(decimal_places=0, max_digits=2)),
                ('n_harga', models.PositiveIntegerField()),
                ('n_ongkir', models.PositiveIntegerField()),
                ('n_diskon', models.PositiveIntegerField()),
                ('n_ratingproduk', models.PositiveIntegerField()),
                ('n_ratingtoko', models.PositiveIntegerField()),
                ('prediksi', models.PositiveIntegerField()),
                ('pelanggan', models.PositiveIntegerField()),
            ],
        ),
    ]
