# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-16 14:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_rekomendasi'),
    ]

    operations = [
        migrations.AddField(
            model_name='rekomendasi',
            name='produk_kategori',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
