# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-16 15:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_rekomendasi_produk_kategori'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rekomendasi',
            name='produk_gambar',
            field=models.ImageField(blank=True, upload_to=b'produk/'),
        ),
    ]
