# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 15:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pelanggan', '0001_initial'),
        ('toko', '0001_initial'),
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('alamat', models.CharField(max_length=250)),
                ('kodepos', models.CharField(max_length=20)),
                ('kabupaten', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('paid', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('harga', models.DecimalField(decimal_places=2, max_digits=10)),
                ('jumlah', models.PositiveIntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='transaksi.Order')),
                ('produk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='shop.Produk')),
            ],
        ),
        migrations.CreateModel(
            name='Transaksi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waktu_pembelian', models.DateTimeField(auto_now_add=True)),
                ('harga', models.DecimalField(decimal_places=2, max_digits=10)),
                ('kategori_harga', models.CharField(max_length=5)),
                ('biaya_pengiriman', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pelanggan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaksi_pelanggans', to='pelanggan.Pelanggan')),
                ('produk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaksi_produks', to='shop.Produk')),
                ('toko', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaksi_tokos', to='toko.Toko')),
            ],
        ),
    ]
