# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 06:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toko', '0001_initial'),
        ('pelanggan', '0002_auto_20170325_2023'),
        ('shop', '0002_auto_20170325_2023'),
        ('transaksi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaksi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waktu_pembelian', models.DateTimeField(auto_now_add=True)),
                ('biaya_pengiriman', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pelanggan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaksi_pelanggans', to='pelanggan.Pelanggan')),
                ('produk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaksi_produks', to='shop.Produk')),
                ('toko', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaksi_tokos', to='toko.Toko')),
            ],
        ),
    ]
