# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-07 01:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pelanggan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ratingtoko',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ratingtoko', models.DecimalField(decimal_places=0, max_digits=2)),
                ('komentar', models.TextField(blank=True)),
                ('pelanggan_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pelangganrt', to='pelanggan.Pelanggan')),
            ],
        ),
        migrations.CreateModel(
            name='Toko',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(db_index=True, max_length=32)),
                ('slogan', models.CharField(max_length=64)),
                ('deskripsi', models.TextField(blank=True)),
                ('alamat', models.CharField(max_length=32)),
                ('pelanggan_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pelanggant', to='pelanggan.Pelanggan')),
            ],
        ),
        migrations.AddField(
            model_name='ratingtoko',
            name='toko_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokor', to='toko.Toko'),
        ),
    ]
